### ISSUE TITLE
在64位mysql5.7.11下安装插件，mysql服务器报错

### ISSUE THREAD

**Issue by smallfang** [yanyiwu/sqljieba#3]
当执行：install plugin sqljieba soname 'libsqljieba.so'
mysql服务器就报错：
2016-04-11T06:55:06.523742Z mysqld_safe Number of processes running now: 0 
2016-04-11T06:55:06.526183Z mysqld_safe mysqld restarted

**Comment by yanyiwu** [comment]
机器内存多大？是不是载入词典的时候内存不够啊。

**Comment by smallfang** [comment]
是词典没有拷贝到/usr/share/dict/，建议安装说明加上下面的命令：

sudo cp ./dict/hmm_model.utf8  /usr/share/dict/hmm_model.utf8
sudo cp ./dict/jieba.dict.utf8  /usr/share/dict/jieba.dict.utf8
sudo cp ./dict/user.dict.utf8  /usr/share/dict/user.dict.utf8

**Comment by yanyiwu** [comment]
@smallfang 谢谢提醒，已经在README上面加上了一句

```
sudo cp -r ./dict /usr/share
```
